<%@ Page Title="" Language="C#" MasterPageFile="~/AdminMaster.master" AutoEventWireup="true" CodeFile="admin_appointments.aspx.cs" Inherits="admin_appointments" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

     <br />
    <br />
    <br />
    <center>
    <table>
        <tr>
            <td align="center">

                <asp:Label ID="Label3" runat="server" Font-Size="X-Large" ForeColor="#3366FF" Text="All Appointment records"></asp:Label>

                <br />
                <br />

            </td>
          </tr>
         <tr>  
            <td>

           
    <asp:GridView ID="GridView1" runat="server" CellPadding="5" ForeColor="#333333" GridLines="None" Height="261px" Width="1236px" AutoGenerateColumns="False" DataKeyNames="A_ID" DataSourceID="SqlDataSource1" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True">
        <AlternatingRowStyle BackColor="White" BorderStyle="None" />
        <Columns>
            <asp:BoundField DataField="A_ID" HeaderText="A_ID" InsertVisible="False" ReadOnly="True" SortExpression="A_ID" />
            <asp:BoundField DataField="P_NAME" HeaderText="P_NAME" SortExpression="P_NAME" />
            <asp:BoundField DataField="PHONE_NO" HeaderText="PHONE_NO" SortExpression="PHONE_NO" />
            <asp:BoundField DataField="EMAIL_ID" HeaderText="EMAIL_ID" SortExpression="EMAIL_ID" />
            <asp:BoundField DataField="INSURANCE" HeaderText="INSURANCE" SortExpression="INSURANCE" />
            <asp:BoundField DataField="DR_NAME" HeaderText="DR_NAME" SortExpression="DR_NAME" />
            <asp:BoundField DataField="SERVICE" HeaderText="SERVICE" SortExpression="SERVICE" />
            <asp:BoundField DataField="A_DATE" HeaderText="A_DATE" SortExpression="A_DATE" />
            <asp:BoundField DataField="A_TIME" HeaderText="A_TIME" SortExpression="A_TIME" />
            <asp:BoundField DataField="CHARGE" HeaderText="CHARGE" SortExpression="CHARGE" />
        </Columns>
        <EditRowStyle BackColor="#2461BF" />
        <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
        <RowStyle BackColor="#EFF3FB" />
        <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
        <SortedAscendingCellStyle BackColor="#F5F7FB" />
        <SortedAscendingHeaderStyle BackColor="#6D95E1" />
        <SortedDescendingCellStyle BackColor="#E9EBEF" />
        <SortedDescendingHeaderStyle BackColor="#4870BE" />
    </asp:GridView>
                <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT [A_ID], [P_NAME], [PHONE_NO], [EMAIL_ID], [INSURANCE], [DR_NAME], [SERVICE], [A_DATE], [A_TIME], [CHARGE] FROM [APPOINT_TBL]" UpdateCommand="UPDATE APPOINT_TBL SET P_NAME =@P_NAME, PHONE_NO =@PHONE_NO, EMAIL_ID =@EMAIL_ID, INSURANCE =@INSURANCE, DR_NAME =@DR_NAME, SERVICE =@SERVICE, A_DATE =@A_DATE, A_TIME =@A_TIME WHERE A_ID=@A_ID" DeleteCommand="DELETE FROM APPOINT_TBL WHERE (A_ID = @A_ID)">
                    <DeleteParameters>
                        <asp:ControlParameter ControlID="GridView1" Name="A_ID" PropertyName="SelectedValue" />
                    </DeleteParameters>
                    <UpdateParameters>
                        <asp:ControlParameter ControlID="GridView1" Name="P_NAME" PropertyName="SelectedValue" />
                        <asp:ControlParameter ControlID="GridView1" Name="PHONE_NO" PropertyName="SelectedValue" />
                        <asp:ControlParameter ControlID="GridView1" Name="EMAIL_ID" PropertyName="SelectedValue" />
                        <asp:ControlParameter ControlID="GridView1" Name="INSURANCE" PropertyName="SelectedValue" />
                        <asp:ControlParameter ControlID="GridView1" Name="DR_NAME" PropertyName="SelectedValue" />
                        <asp:ControlParameter ControlID="GridView1" Name="SERVICE" PropertyName="SelectedValue" />
                        <asp:ControlParameter ControlID="GridView1" Name="A_DATE" PropertyName="SelectedValue" />
                        <asp:ControlParameter ControlID="GridView1" Name="A_TIME" PropertyName="SelectedValue" />
                    </UpdateParameters>
                </asp:SqlDataSource>
         </td>
        </tr>
        </table>
        </center>
</asp:Content>

